name: digivice_app
description: My new Digivice app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  bloc: ^9.0.0
  crypto: ^3.0.6
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  firebase_core: ^3.8.0
  firebase_remote_config: ^5.1.4
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  get_it: ^8.0.2
  injectable: ^2.5.0
  intl: ^0.20.2
  ntp: ^2.0.0
  otp: ^3.1.4
  pointycastle: ^3.9.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.2
  mocktail: ^1.0.4
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
